### ISSUE TITLE
Need some help...

### ISSUE THREAD

**Issue by HelloAlHere** [paypal-examples/docs-examples#10]
I have knowledge of HTML and CSS, but very little regarding API, REST, etc. etc. Is there a more comprehensive resource anyone can point me to which explains the process of implementing PayPal Advanced Checkout step-by-step (in very small steps)? The documentation on PayPal's site is vague and incomplete. As is the documentation within the code posted here. I searched all over the internet, and of course found nothing. I can't be the only one with this problem; I'm sure many other people are attempting to implement this without spending a fortune on a proper development team. Thanks in advance for any help! P.S. I was able to create a page where the requisite customer entry spaces, but the CC areas are not clickable to populate and enter info.

**Comment by monti-star** [comment]
Apologies for such a long time waiting for a response, @HelloAlHere. We've got an updated [YouTube](https://youtu.be/pHbeILqVjOk) video on how to complete this. Hope this helps in the future.
