### ISSUE TITLE
Clearer instructions on Fetch commands

### ISSUE THREAD

**Issue by NullOperator404** [paypal-examples/docs-examples#35]
Without getting off topic, this entire instructional needs to be completely redone with more concise, step-by-step instructions. As others have pointed out, your instructions both on the PP website and here are extremely vague, and you gloss over most of the details. I am well-versed in HTML, CSS, JS, & Node, but your setup simply doesn't work if one follows your instructions. I'm left having to work out most of this myself. 

I have followed your instructions to the letter, but when I run tests in my browser, the `Fetch` command does not recognize "/my-server/create-paypal-order" in the app.js file. The content parameters would suggest this command is trying to call a JSON file, but NO WHERE in your instructions do you clarify what file or what needs to be "fetched" here. It's trying to `fetch` a string of characters, not a JSON file.

Also I'm getting a console error stating that `<!DOCTYPE = html>` is not valid JSON (it's reading my HTML file). Why is it trying to read my parent HTML file, and why does is it looking for JSON there?!

**Comment by NullOperator404** [comment]
I honestly don't expect any response on this, as PayPal is notorious for their poor customer service. But as a developer, I've made a list of items that need attention. Before I begin, you need to understand that not everyone working with this implementation is going to be a senior software developer. You're gonna have to spell things out dummy-proof. So here's what could be improved:

**1. Run `npm install` & 'npm start`.**

You don't bother to explain **_why_** the user needs to do this. You and I understand that it's to start a Node environment for server testing, but average Joes MAY NOT! For one, this won't even WORK if the user hasn't first installed Node, so please update your README to include a preceding step instructing users to install Node if they haven't already. Provide a link to Node's website, FFS. You could at least put in minimal effort. 

**2. Open localhost:8888** 

You're **_assuming_** every developer's local system is going to be running on port 8888. Mine DOESN'T. I use IntelliJ to code/test our HTML/CSS/JS, etc, and our projects run on port 63342. In fact, any IntelliJ users' projects will run on port 63342, not 8888. Furthermore, even if I follow your steps of installing/starting npm, opening this URL returns a "Page Not Found." You don't explain that the user should expect to see their checkout page at this address. Did it not occur to you that some developers may not be using port 8888? In my case, my project is running on port 63342. 

**3. In Index.html, two commands (as you have them written) do not work:**

`fetch("/my-server/create-paypal-order")...`

`fetch("/my-server/capture-paypal-order")...`

What is this!?! Running the code as you have it written will return a 404 "Not Found" error because your `fetch` is not calling an actual file or resource; just a string of characters. Presumably, this needs to be changed to reflect the individual user's setup, **but you don't address this!** Once again, if a lament follows your instructions to the letter, they will not make any changes here and will be stuck getting a 404 error when they run a test. You need to explain clearly what needs to be done here. Give examples, etc. 

**4. In server.js, the same problem as #3 exists:** 

`app.post("my-server/create-paypal-order"...`

`app.post("my-server/capture-paypal-order"...`

These won't work. They look like they're placeholders, but you need to clarify to users that they will need to update these with valid calls. 

Also, the `const = { PORT = 8888}` again assumes the user will be running on port 8888. What if they're NOT?

**5. package.json**

You don't mention this file in ANY of your texts. Is it needed? 

I will be calling customer support tomorrow (Monday, 4/17/2023) to hopefully get some of these issues resolved. The entire instructional needs to be scrapped and you need to start again, this time under the assumption that the user has no knowledge beyond basic HTML.

**Comment by monti-star** [comment]
@NullOperator404, 

Thank you for your honest feedback and also questioning the existing instructions, your perspective will not go unnoticed and we'll work to make this information more helpful.

**Comment by rick-nataniel-walker** [comment]
I am having this same problem as well. The funny thing is I had once used their code in september which looked like this:
`createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{"description":"Efectuar o pagamento do curso agora","amount":{"currency_code":"USD","value":50.91}}]
          });
        },

        onApprove: function(data, actions) {
          return actions.order.capture().then(function(orderData) {

            // Full available details
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));

            // Show a success message within this page, e.g.
            const element = document.getElementById('paypal-button-container');
            element.innerHTML = '';
            element.innerHTML = '<h3>Thank you for your payment!</h3>';

            // Or go to another URL:  actions.redirect('thank_you.html');

          });
        },` 
        
        Yes, with no endpoint and it worked, in fact still works. 
        As for new documentation though I get 404 or CORS error at most. 
        What did I do to solve is I checked the API calls from the dashboard, expecting to see the source URL, but I just got the URI which is v2/checkout/orders. So, I appended the endpoint to the base URL. Well, I still did not manage do fix.
        
        
        I could use the old code, but I am concerned about security issues, I hope there is someone who have solved this problem

**Comment by devchristina** [comment]
The [PayPal documentation](https://developer.paypal.com/docs/checkout/advanced/integrate/#link-beforeyoubeginyourintegration) has answers to the questions posed here. If you're still finding gaps in this information that you feel is necessary to understanding how (or why) this works. Feel free to create a new issue in the repo.
