### ISSUE TITLE
ola soy omar alfonso rodriguez borja cc 72158895 de barranquilla col cuenta en pay pai usuario omar72158895

### ISSUE THREAD

**Issue by omar721588951** [paypal-examples/docs-examples#40]

**Comment by omar721588951** [comment]
[1 (1) (1) (1) (2) (2).pdf](https://github.com/paypal-examples/docs-examples/files/11391879/1.1.1.1.2.2.pdf)
[72158895 (1) omar (1) (2) (1) (2) (1) (1).pdf](https://github.com/paypal-examples/docs-examples/files/11391880/72158895.1.omar.1.2.1.2.1.1.pdf)
[cedula (omar alfonso rodriguez borja) (omar alfonso rodriguez borja) (4) (1) (1) (1) (1) (2) (1) (2) (1) (2) (1) (1) (1) (1) (1) (1).pdf](https://github.com/paypal-examples/docs-examples/files/11391881/cedula.omar.alfonso.rodriguez.borja.omar.alfonso.rodriguez.borja.4.1.1.1.1.2.1.2.1.2.1.1.1.1.1.1.pdf)
[CertificadoLibretaMilitar (1) (1) (1) (1) (3) (6) (1) (2).pdf](https://github.com/paypal-examples/docs-examples/files/11391882/CertificadoLibretaMilitar.1.1.1.1.3.6.1.2.pdf)

**Comment by monti-star** [comment]
Closing as spam
