### ISSUE TITLE
comfirmo omar alfonso rodriguez borja cc 72158895 de barranquilla colombia

### ISSUE THREAD

**Issue by shango420** [paypal-examples/docs-examples#41]
comfirmo omar alfonso rodriguez borja cc 72158895 de barranquilla colombia

_Originally posted by @omar721588951 in https://github.com/paypal-examples/docs-examples/issues/36#issuecomment-1516945548_

**Comment by za8457** [comment]
zk899104@gmail.com #40

**Comment by shango420** [comment]
https://github.com/paypal-examples/docs-examples/issues/41#issue-1677521488

**Comment by omar721588951** [comment]
commformida no seguir si
