### ISSUE TITLE
payment is api is giving success but not detecting from acccount

### ISSUE THREAD

**Issue by shafqatjanhashe** [paypal-examples/docs-examples#51]
Hello im trying to integrate advance and everything is giving success and transaction completed but when i go to paypal account my funds remain same, when i try paypal button and transaction completed funds are detecting

**Comment by devchristina** [comment]
Hi @shafqatjanhashe -- Apologies for such a delay in a response to this issue. Are you still facing this issue?

**Comment by devchristina** [comment]
Due to lack of response, I will close this issue as not planned. If you're still facing this issue please either re-open or create a new issue.
