### ISSUE TITLE
Eeeee

### ISSUE THREAD

**Issue by shango420** [paypal-examples/docs-examples#94]
Braintree > Pagar con integración de PayPal

**Comment by shango420** [comment]
> Braintree > Pagar con integración de PayPal

**Comment by shango420** [comment]
https://api-m.paypal.com/v2/checkout/orders

**Comment by shango420** [comment]
[]()https://api-m.paypal.com/v2/checkout/orders

**Comment by gm7231015** [comment]
Good

**Comment by shango420** [comment]
> Good 

c4ee30fb101f3b2ea4a3665a37c7beca65fb02b5

**Comment by shango420** [comment]
> Good 

https://paypal.me/xhangtech?country.x=MX&locale.x=es_XC

**Comment by devchristina** [comment]
Closing, not planned. Spam.

**Comment by shango420** [comment]
ARUmG_P1I17Vs-9Hn_Tcn5cklPmJNOkCSoVSrXpfm1U3QgIlqV1nj6UsklUBN7yhn5DGLVLXNngGiLgh

**Comment by shango420** [comment]
> 9Hn_Tcn5cklPmJNOkCSoVSrXpfm1U3QgIlqV1nj6UsklUBN7yhn5DGLVLXNngGiLgh
