### ISSUE TITLE
Mioooo

### ISSUE THREAD

**Issue by shango420** [paypal-examples/docs-examples#95]
AfsfqefxvATf2j_1gEqXHNJow-9gdooRv-IMK_YuTZ10uMXJKF47T1MQ8I9hYO1-VTA1lYiTdvos7eRD

**Comment by shango420** [comment]
> AfsfqefxvATf2j_1gEqXHNJow-9gdooRv-IMK_YuTZ10uMXJKF47T1MQ8I9hYO1-VTA1lYiTdvos7eRD

sb-bmgjg15186912_api1.business.example.com

**Comment by devchristina** [comment]
Closing, not planned. Spam.
